'''
    根据指令生成提示词
'''

from langchain_core.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
)


# _human_message_template = (
#     "Here is a task description for which I would like you to create a high-quality prompt template for:\n"
#     "<task_description>\n"
#     "{instruction}\n"
#     "</task_description>\n"
#     "Based on task description, please create a well-structured prompt template that another AI could use to consistently complete the task. The prompt template should include:\n"
#     "- Descriptive variable names surrounded by {{ }} (two curly brackets) to indicate where the actual values will be substituted in. Choose variable names that clearly indicate the type of value expected. Variable names have to be composed of number, english alphabets and underline and nothing else. \n"
#     "- Clear instructions for the AI that will be using this prompt, demarcated with <instructions> tags. The instructions should provide step-by-step directions on how to complete the task using the input variables. Also Specifies in the instructions that the output should not contain any xml tag. \n"
#     "- Relevant examples if needed to clarify the task further, demarcated with <example> tags. Do not use curly brackets any other than in <instruction> section. \n"
#     "- Any other relevant sections demarcated with appropriate XML tags like <input>, <output>, etc.\n"
#     "- Use the same language as task description. \n"
#     "- Output in ``` xml ``` and start with <instruction>\n"
#     "Please generate the full prompt template and output only the prompt template.\n"
# )

'''
    Template variables:
      - instruction: 用户指令
'''
_human_message_template = (
    "### Task\n"
    "You are an expert in designing prompt templates for large language models.\n"
    "\n"
    "Your task is to generate a complete prompt template in XML format based on a given task description.\n"
    "You should respond in the same language as the provided task description.\n"
    "<task_description>\n"
    "{instruction}\n"
    "</task_description>\n"
    "\n"
    "### Steps to Follow\n"
    "Step 1: Identify the purpose of the chatbot from the task description.\n"
    "Step 2: Analyze the language of the task description. You should answer in the same language.\n"
    "Step 3: Based on the understanding of the task description, generate responses in the constrained XML format and language.\n"
    "\n"
    "### Constraint\n"
    "The template must follow these structure and formatting rules:\n"
    "\n"
    "1. The entire template must be wrapped in a single `<instruction>` tag.\n"
    "2. Inside `<instruction>`, include the following sections:\n"
    "   - `<description>`: A brief and clear description of the task.\n"
    "   - `<input>`: Define any input variables required to complete the task. Each variable should be named clearly and meaningfully.\n"
    "     - Within `<input>`, you need to describe the meaning of the variable, e.g., `<variable_name>the meaning of the variable</variable_name>`.\n"
    "   - `<output>`: Describe the expected output format or structure.\n"
    "   - `<example>`: Provide one or more relevant examples that illustrate how to perform the task.\n"
    "   - `<instructions>`: Provide clear, step-by-step instructions that guide the AI on how to use **all** input variables to complete the task.\n"
    "     - Within `<instructions>`, you need to describe the processing steps with serial numbers, e.g., `1. ... 2. ...`\n"
    "     - Within `<instructions>`, **enclose all variable names in double curly braces**, e.g., `{{{{variable_name}}}}`.\n"
    "\n"
    "Additional requirements:\n"
    "- Use only English letters, numbers, and underscores in variable names.\n"
    "- Do not include any XML tags in the output generated by the AI that uses the prompt template.\n"
    "- Output the final result inside a single code block using triple backticks and the `xml` language label.\n"
    "- All content **within the XML template** (including section names and values) must be written in the same language as the task description.\n"
    "- Please answer in the same language as the task description language. \n"
    "- 如果任务描述是中文的，请使用中文回答。\n"
    "- If the task description is in English, please answer in English.\n"
    "\n"
    "Only return the final prompt template. Do not include any explanations or commentary.\n"
    "/no_think"
)

PROMPT_TEMPLATE_GENERATE_PROMPT = ChatPromptTemplate.from_messages(
    messages=[
        HumanMessagePromptTemplate.from_template(_human_message_template),
    ]
)
